### ISSUE TITLE
v1.0.0 question

### ISSUE THREAD

**Issue by gabeio** [expressjs/multer#162]
So currently (v1.0.0) there is no way to mount multer globally (within the app) `app.use(multer` or only if it accepts files?

**Comment by jpfluger** [comment]
You could do something like this:

```javascript
var express = require('express');
var app = express();
var multer  = require('multer');

app.use(multer({ dest: 'uploads/' }).fields([{ name: 'avatar', maxCount: 1 }]));
```
But mounting globally is not recommended. Best practice is to create middleware on the route (eg post), define the fieldname of the input html element with a limit (eg `{ name: 'avatar', maxCount: 1 }`. This helps prevents an attack in the old multer wherein an attacker could flood a server with posts, sending files, and the server would accept those files until it crashed.

If `maxCount` is not defined, than maxCount becomes "infinity", which is part of the hole we are trying to limit in the old multer.

Would it be useful if we had something in the README that explained this?

**Comment by gabeio** [comment]
I don't allow file uploads currently and my nginx running in front of all the nodes is limiting the requests to ~5mb each giving ample room if a user really wants to post something large...

I tried running multer like before... globally but without the `.fields()` is that now required?

> Would it be useful if we had something in the README that explained this?

probably :smile:

**Comment by gabeio** [comment]
I think the confusion is coming in that there is still things like `app.use(multer({ dest: 'uploads/' }))` in the readme...

**Comment by jpfluger** [comment]
Yes, this is a truly breaking release with a few humps :camel: but we do have our reasons for them. 

The reason `multer({ dest: 'uploads/' })` is around is b/c now it is assigned to a variable that can be reused to create the middleware on the route, such as in the docs:

```javascript
var multer = multer({ dest: 'uploads/' });

// used once 
app.post('/profile', upload.single('avatar'), function (req, res, next) {
  // req.file is the `avatar` file
})

// used twice
app.post('/photos/upload', upload.array('photos', 12), function (req, res, next) {
  // req.files is array of `photos` files
})

// used thrice
var cpUpload = upload.fields([{ name: 'avatar', maxCount: 1 }, { name: 'gallery', maxCount: 8 }])
app.post('/cool-profile', cpUpload, function (req, res, next) {
  // req.files is an object (String -> Array) where fieldname is the key, and the value is array of files
})
```

The parameters for `.fields()` takes route-specific parameters (eg fieldname), so that's why those options are there.

ping @LinusU - I remember before the release we talked about possibly allowing `.fields()` to take any fieldname with a qualifying parameter, something like `.fields('*')`. Can't find it in the code so maybe we left it out to try to force security. That sound right?

**Comment by gabeio** [comment]
the * would be nice! :) or to have something like `multer.fields(<count>)` instead of actually having the names and all... that way I can limit but still not have to have every single possible field name...

**Comment by gabeio** [comment]
@jpfluger tedious:
```
.fields([{ name: "aid" },{name: "title"},{name:"text"},{name:"tries"},{name:"opendate"},{name:"opentime"},{name:"closedate"},{name:"closetime"},{name:"late"},{name:"total"}])
```
& that is not including the maxCount which btw is optional? Didn't you say that was part of the hole you were trying to fix in the old multer?

**Comment by jpfluger** [comment]
Yes, tedious as best practices sometimes are.... I don't have a problem adding in a .fields('*') so long as we update the documentation and provide reasons for why this is not recommended. Let's see if @LinusU has any thoughts.

**Comment by gabeio** [comment]
I guess you're right they sometimes are I'd rather not add a way out :smile:...

**Comment by LinusU** [comment]
@gabeio I just want to clarify that this only applies to files, not normal input fields. From the example you gave it looks like maybe you thought it also applied to text fields.

The reasoning for this is that fields are allocated in memory and is dropped when the request is done and often doesn't contain nearly enough data so the default limits is lower for fields. Files on the other hand are written to disk and thus will stick around after the request is completed.

You can read more about the security reasoning in #133. Here is a part of that discussion:

> **1) Adding `multer` as a global handler**

> `app.use(multer({ ... }))`

> This is bad because the application will accept files to any endpoint even though the user only handles it in a few of them.

> ```javascript
app.use(multer({ ... }))

> app.post('/upload-picture', function (req, res, next) {
  req.files['pic'].forEach(function (file) {
    // Move the file to the users library
  })
})

> // A malicious user could now upload any files and stick them into the
// temporary directory by making a POST request to any invalid url.
//
// e.g. POST a huge file to /blah
```

> **2) Not handling every uploaded file**

> If the user adds multer only to one route, but doesn't specify a file name filter, it's again possible to upload files that won't be handled.

> ```javascript
var upload = multer({ ... })
  
> app.post('/upload-picture', upload, function (req, res, next) {
  req.files['pic'].forEach(function (file) {
    // Move the file to the users library
  })
})

> // A malicious user could now upload any files and stick them into the
// temporary directory by making a POST request with an unexpected fieldname.
//
// e.g. POST a huge file with the fieldname blah to /upload-picture
```

**Comment by LinusU** [comment]
Also, there was actually `.use(multer( ... ))` usage that got thru to the readme, I've fixed that with 54037c8069b8c26f294a5fd6c8151460a511054d.

**Comment by gabeio** [comment]
> Also, there was actually .use(multer( ... )) usage that got thru to the readme, I've fixed that with 54037c8.

@LinusU glad to see you fixed them! ;]

> I just want to clarify that this only applies to files, not normal input fields. From the example you gave it looks like maybe you thought it also applied to text fields.

Sorry, this actually just confused me more. lol What were you referring to...? The reasoning behind this change? I get that the files are large & they end up sticking around... that I am totally okay with needing to say yes to accept them... but the fields I feel aren't as crazy... but in the end I came to the realization (thanks @jpfluger :smile:) that by defining which fields should also be accepted is probably best as I actually found some (currently) unnecessary fields (previously necessary) which I hadn't updated...

**Comment by LinusU** [comment]
@gabeio Hehe, so what I was trying to say was that you only have to specify which files to accept. All normal fields will be accepted.

E.g. this form:

```html
<form>

  <input type="text" name="firstname" />
  <input type="text" name="lastname" />

  <input type="file" name="avatar" />
  <input type="file" name="background" />

</form>
```

Only needs this code to accept it:

```javascript
var profileUpload = upload.fields([
  { name: 'avatar', maxCount: 1 },
  { name: 'background', maxCount: 1 }
])

app.post('/profile', profileUpload, function (req, res) {
  
  // Fields
  req.body.firstname
  req.body.lastname

  // Files
  req.files.avatar[0]
  req.files.background[0]

})
```

**Comment by gabeio** [comment]
OH, wow. I just finished doing the `.fields([` for half of my app's fields. :laughing: SO I only need to move multer to each router/route `app.post('/route',upload,func` that needs to accept fields? or am I still missing something? and if so how do I only define I want fields? it sounds like I need to use `.array()` `.fields()` `.single()` but I want no files... I guess I could do `.fields([])` with a blank array...

**Comment by LinusU** [comment]
Ouch, oh well, at least you detected the fields that weren't used :)

Hmm, that's a good question about routes without files. Are you still uploading the form with `enctype="multipart/form-data"`. Normally that is only used when you also have files.

Multer only parses `multipart/form-data` but `busboy` (the library that we are using) supports the more common `application/x-www-form-urlencoded` as well. We could start accepting both which I kind of think makes more sense... Maybe...

I guess right now you could do `.fields([])` but that seems a bit unclear. The reason it is like this is because `multer` is very focused on file uploading, the fact that it also parses text fields is more of secondary thing.

Maybe something like `.noFiles()` would make sense... But then it would be much better to just use `application/x-www-form-urlencoded` since that has a lot (and I do mean a lot!) less overhead. That could be parsed by [express body-parser](https://github.com/expressjs/body-parser) like so:

```javascript
app.post('/route', bodyParser.urlencoded(), function (req, res) {

})
```

What api would suit your use case best?

**Comment by gabeio** [comment]
well see the future isn't clear if I am going to start allowing file uploads or not but 99% of the routes that allow post/put would allow file uploads so I guess I will just stick with multer for now so if I do decide to allow uploads later I can just add that with a lot more ease... and yeah all my forms already have multipart/form-data and if I eventually decide to never allow file uploads I might look into something with less overhead :grin: thanks for the super support! :+1:
