### ISSUE TITLE
How I can limit file size?

### ISSUE THREAD

**Issue by realsagi** [expressjs/multer#314]
i use **[.fields(fields)]**  for upload image.
i need limit file size of each fields.
Can I do it? How?
thank you

**Comment by LinusU** [comment]
It isn't supported currently...

**Comment by realsagi** [comment]
thank you LinusU

**Comment by djlxiaoshi** [comment]
you can do it as follow:
multer({
    storage: storage,
    limits:{
    	fileSize:1000  //size of u file
    },
    fileFilter:fileFilter
});

**Comment by DiegoRBaquero** [comment]
This can be closed.

**Comment by LinusU** [comment]
> i need limit file size of each fields.

I don't think that this use case is solved yet...

**Comment by jagged3dge** [comment]
There still needs to be a way to provide individual limits for when handling multiple form fields with different fieldnames.

My suggestion:
The `limits` could take a function as well as an object (default). This function would be called with `(file, cb)` args, so that the `fieldname` could be accessed via the `file` object, just like you'd do for `fileFilter`.

**Comment by 2pay** [comment]
You test on this option:

    var upload = multer({
        ...
        limits: { fileSize: settings.maxSizeUpload }, //In settings.maxSizeUpload: 1 * 1024 * 1024 // 1MB
      ...
    }).fields([{ name: 'avatar', maxCount: 1 }, { name: 'avatar2', maxCount: 2 }]);

In Router.post:

    upload(req, res, function(err) {
        if (err) {
            //Handle error
            return res.end("Something went wrong!" + err);
        }
        res.redirect('/users/dashboard');
    });

goodluck!

**Comment by fndaru** [comment]
@2pay OP's question is about having a different size limit for each field. Your suggestion doesn't solve that.

**Comment by TusharRoy23** [comment]
var storage = multer.diskStorage({
  destination: (req, file, callback) => {
    callback(null, "./public/uploads/");
  },
  filename: (req, file, callback) => {
    callback(null, Date.now() + file.originalname);
  }
});

app.use(
  multer({
    storage: storage,
    fileFilter: function(req, file, callback) {
      var type = file.mimetype;
      var typeArray = type.split("/");

      if (typeArray[0] == "image") {
        callback(null, true);
      } else {
        callback(null, false);
      }
    }
  }).fields([
    {
      name: "photo"
    },
    { name: "picture" }
  ])
);
module.exports = app;

This one is OK for preventing PDF flies

But, i need individual fileFilter in fields() 
Like this,
.fields([
    {
      name: "photo", fileFilter: function( req, file, callback){ Image Upload}
    },
    { name: "PDF",  fileFilter: function( req, file, callback){ PDF Upload}}
  ])

Is it possible ?
If that, is anyone here to solve this issue ?
Or suggest any better approach.
Thank You

**Comment by jagged3dge** [comment]
@TusharRoy23 Thank you for taking the time to post (while keeping it illegible). 
However, it doesn't solve the OP's question. 
Your piece of code limits the type of file (by mimetype). 

The OP's question is regarding limiting the **file size** of the valid file(s) that have passed the `fileFilter` function.

Reiterating @fndaru 's reply to a previous attempt at an answer:  
> OP's question is about having a different size limit for each field. Your suggestion doesn't solve that.

**Comment by nystest** [comment]
### ### ### ### ### ### ### ### ### ### ### gw

**Comment by nystest** [comment]
> ### _**yes**_

**Comment by mimoid-prog** [comment]
2021 and still no solution for this?  There are two answers and both are wrong.

**Comment by mohammadyaser** [comment]
@mimoid-prog I used  `+req.rawHeaders.slice(-1)[0]` get the size file and write a business logic in fileFilter
```
const multer = require('multer');
const { v4: uuid } = require("uuid");

const TYPE_IMAGE = {
  'image/png': 'png',
  'image/jpeg': 'jpeg',
  'image/jpg': 'jpg'
};
const TYPE_File = {
  'application/pdf': 'pdf',
};

const fileUpload = 
  multer({
    limits: 500000, 
    storage: multer.diskStorage({
      destination: (req, file, cb) => {
        cb(null, 'uploads/images');
      },
      filename: (req, file, cb) => {
        const ext = (TYPE_IMAGE[file.mimetype]) ? TYPE_IMAGE[file.mimetype] : TYPE_File[file.mimetype];
        cb(null, uuid() + '.' + ext);
      }
    }),
    fileFilter: (req, file, cb) => {
      let size = +req.rawHeaders.slice(-1)[0]
      let isValid =false;
      if(!!TYPE_IMAGE[file.mimetype] && size < 4 * 1024 * 1024  ){
        isValid = true
      }
      if(!!TYPE_File[file.mimetype] && size < 1 * 1024 * 1024  ){
        isValid = true
      }
      let error = isValid ? null : new Error('Invalid mime type!');
      cb(error, isValid);
    }
  }).any();


module.exports = fileUpload;

**Comment by Saikedo** [comment]
Any updates on this issue?
