### ISSUE TITLE
Error: Unexpected end of multipart data

### ISSUE THREAD

**Issue by soakit** [expressjs/multer#350]
Error: Unexpected end of multipart data
    at C:\Users\admin\Desktop\wap\static\node_modules\dicer\lib\Dicer.js:62:28
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickDomainCallback (node.js:390:13)

Server
> var upload = multer();
> router.post('/foo', upload.single('file'), function (req, res, next) {
>     console.log('foo');
> });

client:

> ClientRequest {                                                                                                                                                     
>   domain: null,                                                                                                                                                     
>   _events:                                                                                                                                                          
>    { response: { [Function: g] listener: [Function] },                                                                                                              
>      socket: { [Function: g] listener: [Function] } },                                                                                                              
>   _eventsCount: 2,                                                                                                                                                  
>   _maxListeners: undefined,                                                                                                                                         
>   output:                                                                                                                                                           
>    [ 'POST /foo HTTP/1.1\r\nContent-Type: multipart/form-data; boundary=-----np0.6452500836458057\r\nContent-Length: 286\r\nHost: localhost:8009\
> r\nConnection: close\r\n\r\n-------np0.6452500836458057\r\n',                                                                                                       
>      'Content-Disposition: form-data; name="to"\r\n',                                                                                                               
>      '\r\n',                                                                                                                                                        
>      '/data/static/admin/160601index/html/哈哈.html\r\n',                                                                                                       
>      '-------np0.6452500836458057\r\n',                                                                                                                             
>      'Content-Disposition: form-data; name="file"; filename="/html/哈哈.html"\r\n',                                                                                   
>      '\r\n',                                                                                                                                                        
>      <Buffer 61 61 61 0d 0a 62 62 62 0d 0a 61 61 61 0d 0a 61 62 63 0d 0a 61 73 73 61 0d 0a 73 73>,                                                                  
>      '\r\n',                                                                                                                                                        
>      '-------np0.6452500836458057--\r\n' ],                                                                                                                         
>   outputEncodings:                                                                                                                                                  
>    [ undefined,                                                                                                                                                     
>      undefined,                                                                                                                                                     
>      undefined,                                                                                                                                                     
>      undefined,                                                                                                                                                     
>      undefined,                                                                                                                                                     
>      undefined,                                                                                                                                                     
>      undefined,                                                                                                                                                     
>      undefined,                                                                                                                                                     
>      undefined,                                                                                                                                                     
>      undefined ],                                                                                                                                                   
>   outputCallbacks:                                                                                                                                                  
>    [ undefined,                                                                                                                                                     
>      undefined,                                                                                                                                                     
>      undefined,                                                                                                                                                     
>      undefined,                                                                                                                                                     
>      undefined,                                                                                                                                                     
>      undefined,                                                                                                                                                     
>      undefined,                                                                                                                                                     
>      undefined,                                                                                                                                                     
>      undefined,                                                                                                                                                     
>      undefined ],                                                                                                                                                   
>   outputSize: 462,                                                                                                                                                  
>   writable: true,                                                                                                                                                   
>   _last: true,                                                                                                                                                      
>   chunkedEncoding: false,                                                                                                                                           
>   shouldKeepAlive: false,                                                                                                                                           
>   useChunkedEncodingByDefault: true,                                                                                                                                
>   sendDate: false,                                                                                                                                                  
>   _removedHeader: { 'content-length': false },                                                                                                                      
>   _contentLength: null,                                                                                                                                             
>   _hasBody: true,                                                                                                                                                   
>   _trailer: '',                                                                                                                                                     
>   finished: false,                                                                                                                                                  
>   _headerSent: true,                                                                                                                                                
>   socket: null,                                                                                                                                                     
>   connection: null,                                                                                                                                                 
>   _header: 'POST /foo HTTP/1.1\r\nContent-Type: multipart/form-data; boundary=-----np0.6452500836458057\r\nContent-Length: 286\r\nHost: localhost
> :8009\r\nConnection: close\r\n\r\n',                                                                                                                                
>   _headers:                                                                                                                                                         
>    { 'content-type': 'multipart/form-data; boundary=-----np0.6452500836458057',                                                                                     
>      'content-length': 286,                                                                                                                                         
>      host: 'localhost:8009' },                                                                                                                                      
>   _headerNames:                                                                                                                                                     
>    { 'content-type': 'Content-Type',                                                                                                                                
>      'content-length': 'Content-Length',                                                                                                                            
>      host: 'Host' },                                                                                                                                                
>   _onPendingData: null,                                                                                                                                             
>   agent:                                                                                                                                                            
>    Agent {                                                                                                                                                          
>      domain: null,                                                                                                                                                  
>      _events: { free: [Function] },                                                                                                                                 
>      _eventsCount: 1,                                                                                                                                               
>      _maxListeners: undefined,                                                                                                                                      
>      defaultPort: 80,                                                                                                                                               
>      protocol: 'http:',                                                                                                                                             
>      options: { path: null },                                                                                                                                       
>      requests: {},                                                                                                                                                  
>      sockets: { 'localhost:8009:': [Object] },                                                                                                                      
>      freeSockets: {},                                                                                                                                               
>      keepAliveMsecs: 1000,                                                                                                                                          
>      keepAlive: false,                                                                                                                                              
>      maxSockets: Infinity,                                                                                                                                          
>      maxFreeSockets: 256 },                                                                                                                                         
>   socketPath: undefined,                                                                                                                                            
>   method: 'POST',                                                                                                                                                   
>   path: 'foo' }                                                                                                                                 
>                                                                                                                                                                     

console

> events.js:141                                                                                                                                                       
>       throw er; // Unhandled 'error' event                                                                                                                          
>       ^                                                                                                                                                             
>                                                                                                                                                                     
> Error: socket hang up                                                                                                                                               
>     at createHangUpError (_http_client.js:200:15)                                                                                                                   
>     at Socket.socketOnEnd (_http_client.js:292:23)                                                                                                                  
>     at emitNone (events.js:72:20)                                                                                                                                   
>     at Socket.emit (events.js:166:7)                                                                                                                                
>     at endReadableNT (_stream_readable.js:913:12)                                                                                                                   
>     at nextTickCallbackWith2Args (node.js:442:9)                                                                                                                    
>     at process._tickCallback (node.js:356:17)

**Comment by LinusU** [comment]
It's very hard to understand exactly what's going on from your post, but it seems like the connection between the server and the client got interrupted somehow.

Hence the `Error: socket hang up` on the client, and `Error: Unexpected end of multipart data` on the server.

Can you provide any more information?

**Comment by soakit** [comment]
I have fixed it.
Because the Chinese file name, use `encodeURIComponent`

**Comment by 91robin** [comment]
Any idea in which minimum version of multer, this issue was solved.

Actually issue was coming due to chinese characters in uploading file

**Comment by mrmedina87** [comment]
@soakit How did you made the chinese file name to avoid using the encodeURIComponent ?

**Comment by soakit** [comment]
example:
```js
const fileName = encodeURIComponent ('/文件夹/例子.js'); // means /folder/example.js
```
@mrmedina87

**Comment by mrmedina87** [comment]
Thanks!

**Comment by softmarshmallow** [comment]
Using ascii file name, still getting the same error. Hmm... using with nestjs + serverless.

**Comment by hitesh22b** [comment]
> Using ascii file name, still getting the same error. Hmm... using with nestjs + serverless.

Same stack brother, facing the same issue.
Were you able to solve it?

**Comment by azeez-abp** [comment]
Error: Unexpected end of form
      at Multipart._final (C:\Users\BONJOUREX\Desktop\nodesoft\node_modules\busboy\lib\types\multipart.js:588:17) 
      at callFinal (internal/streams/writable.js:610:10)
      at processTicksAndRejections (internal/process/task_queues.js:82:21) {
    storageErrors: []

I am using multer to upload file on nodeJS backend
Any idea on how to fix this problem

**Comment by shopnilashik** [comment]
Error: Unexpected end of form
    at Multipart._final (/Users/ashikurrahman/Downloads/all Projects/Full Stack with Nodejs/server/node_modules/busboy/lib/types/multipart.js:588:17)
    at callFinal (node:internal/streams/writable:694:27)
    at prefinish (node:internal/streams/writable:719:7)
    at finishMaybe (node:internal/streams/writable:729:5)
    at Multipart.Writable.end (node:internal/streams/writable:631:5)
    at IncomingMessage.onend (node:internal/streams/readable:693:10)
    at Object.onceWrapper (node:events:509:28)
    at IncomingMessage.emit (node:events:402:35)
    at endReadableNT (node:internal/streams/readable:1343:12)

i'm also facing same error. i'm using multer for file upload on nodejs

**Comment by apbuddy10** [comment]
> Error: Unexpected end of form at Multipart._final (C:\Users\BONJOUREX\Desktop\nodesoft\node_modules\busboy\lib\types\multipart.js:588:17) at callFinal (internal/streams/writable.js:610:10) at processTicksAndRejections (internal/process/task_queues.js:82:21) { storageErrors: []
> 
> I am using multer to upload file on nodeJS backend Any idea on how to fix this problem

Same issue even I am facing

**Comment by HanOterLin** [comment]
About error ”Error: Unexpected end of form“,
please check if you are calling the multer middleware multiple times.
@shopnilashik @azeez-abp

**Comment by johnbabu021** [comment]
i also faced the issue the reason is data is not getting to the server side properly it's a bug on client side

**Comment by xxc-yqxz** [comment]
> i also faced the issue the reason is data is not getting to the server side properly it's a bug on client side

Any idea on how to fix this problem?

**Comment by xxc-yqxz** [comment]
@apbuddy10 @shopnilashik I tried to switch the Multer version to 1.4.4, this problem will not occur, maybe it is the defect of the new version?

**Comment by RecaMedia** [comment]
> i also faced the issue the reason is data is not getting to the server side properly it's a bug on client side

Do you have a solution on how to resolve what is happening client side?

**Comment by fafamnzm** [comment]
I had the same issue. my error was with using multer as an async function inside the middleware and I messed up the use of next function, as it is different with callbacks and async function. 
check this solution, see if this works

**Comment by sigott** [comment]
@fafamnzm Would you mind posting your middleware code?  I'm running into the same issue and suspect it's the problem you describe but I'm not sure what I should change.
Thanks.

**Comment by fafamnzm** [comment]
```typescript
export function mediaErrorHandler(err, req, res, next) {
            if (err) {
	            res.json({ error: "something went wrong});
	            return next("error happened");
            }
	return next();
}

```

now how does this middleware function accept four params and how does node understand that it is the error middleware, is beyond my current time to discover

cause when something happens and you return a next with anything inside of it (`next("error")`) , it will get to this middleware right away 
and when you return next with another thing inside of it, it will skip all other middlewares!

if I am doing something wrong and anyone knows any better way to do this, please let me know.

I hope this works

**Comment by kushkapadia** [comment]
> encodeURIComponent

Where should this be added? I am getting the same issue. Cannot find any way to solve.
Please help. 
Thanks and regards,
Kush Kapadia

**Comment by sigott** [comment]
@kushkapadia 
FYI, I abandoned using Multer and just went with busboy.   using the code below.  It's not a clean solution and requires loading the entire file into a virtual filesystem first, which introduces memory issues and file size limits but it works. 

```
exports.uploadFile = async (req: any, res: any) => {
  const busboy = BusBoy({ headers: req.headers });
  const storage = new Storage();
  let uploadFile: any = {};

  busboy.on("file", (fieldname: any, file: any, fileInfo: any) => {
    const { uuid, storageFileName } = generateStorageFileName(fileInfo.filename);
    uploadFile.originalName = fileInfo.filename;
    uploadFile.mimeType = fileInfo.mimeType;
    uploadFile.storageFileName = storageFileName;
    uploadFile.uuid = uuid;
    uploadFile.tempPath = path.join(os.tmpdir(), uuid);

    file.pipe(fs.createWriteStream(uploadFile.tempPath));
  });

  busboy.on("finish", async () => {
    const subdomain = getClientDomainfromRequest(req)
    const folderName = generateFolderName(subdomain);

    let storageOptions: any = {};
    storageOptions = {
      resumable: false,
      destination: `${folderName}/${uploadFile.uuid}`,
      metadata: {
        metadata: {
          originalName: uploadFile.originalName,
          uuid: uploadFile.uuid,
          processStatus: '0',
          processDesc: 'Upload'
        }
      }
    }

    const storage = new Storage();
    const bucket = storage.bucket(uploadBucketName);
    bucket.upload(uploadFile.tempPath, storageOptions)
      .then(async () => {
        const uuid = uploadFile.uuid;
        return res.json({ uuid, message: "File Uploaded Successfully" });
      })
      .catch((err: any) => {
        console.error(err);
        return res.status(400).json({ error: err.code });
      });
  });
  busboy.end(req.rawBody);
};

```

**Comment by aegisfiveniner** [comment]
i had my issue solved by replacing 

express.urlencoded() with bodyParser.urlencoded()

const bodyParser = require ("body-parser")

**Comment by azeez-abp** [comment]
congratulations
